PREFIX projet: <http://websm.org/projet/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia-fr: <http://fr.dbpedia.org/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

#Régions
CONSTRUCT
{
  ?URI a projet:Region;
    owl:sameAs ?sameAs;
    rdf:label ?label
}
FROM <file:donnees.csv>
WHERE {
  BIND (URI(CONCAT("projet:", REPLACE(?reg_nom, "\\s+", "_"))) as ?URI)
  BIND (URI(CONCAT("dbpedia-fr:", REPLACE(?reg_nom, "\\s+", "_"))) as ?sameAs)
  BIND (REPLACE(?reg_nom, "\\s+", "_") as ?label)
}

#Départements
CONSTRUCT
{
  ?URI a projet:Departement;
    owl:sameAs ?sameAs;
    rdf:label ?label
}
FROM <file:donnees.csv>
WHERE {
  BIND (URI(CONCAT("projet:", REPLACE(?dep_nom, "\\s+", "_"))) as ?URI)
  BIND (URI(CONCAT("dbpedia-fr:", REPLACE(?dep_nom, "\\s+", "_"))) as ?sameAs)
  BIND (REPLACE(?dep_nom, "\\s+", "_") as ?label)
}

#Twitter
CONSTRUCT {
  ?URI a foaf:OnlineAccount;
    foaf:accountName ?name;
    foaf:accountServiceHomepage "http://twitter.com/"
}

FROM <file:donnees.csv>
WHERE {
  BIND (REPLACE(?compte_twitter, "https://twitter\\.com/", "") as ?name)
  BIND (URI(?compte_twitter) as ?URI)
}

#LinkedIn
CONSTRUCT {
  ?URI a foaf:OnlineAccount;
    foaf:accountName ?name;
    foaf:accountServiceHomepage "http://www.linkedin.com/"
}

FROM <file:donnees.csv>
WHERE {
  BIND (REPLACE(?compte_linkedin, "(http|https)://[a-z]*\\.linkedin\\.com/", "") as ?name)
  BIND (URI(?compte_linkedin) as ?URI)
}

#Institutions
CONSTRUCT {
	?URI a projet:Institution;
    projet:uai ?uai;
    projet:libelle_court ?libelle_court;
    projet:libelle_long ?libelle_long;
    projet:statut_juridique_court ?statut_juridique_court;
    vcard:street-address ?adresse;
    projet:complement_adresse ?complement_adresse;
    vcard:postal-code ?code_postal;
    vcard:locality ?uri_localite;
    vcard:latitude ?latitude;
    vcard:longitude ?longitude;
    vcard:url ?site_internet;
    foaf:account ?uri_twitter;
    foaf:account ?uri_linkedin;
    projet:identifiant_freebase ?identifiant_freebase;
    projet:identifiant_wikidata ?identifiant_wikidata;
    projet:statut_operateur_lolf ?statut_operateur_lolf;
    projet:libelle_mission_chef_de_file ?libelle_mission_chef_de_file;
    projet:identifiant_programme_lolf_chef_de_file ?identifiant_programme_lolf_chef_de_file;
    projet:libelle_programme_lolf_chef_de_file ?libelle_programme_lolf_chef_de_file;
    projet:identifiants_autres_programmes_lolf ?identifiants_autres_programmes_lolf;
    projet:libelles_autres_programmes_lolf ?libelles_autres_programmes_lolf;
    projet:com_code ?com_code;
    projet:com_nom ?com_nom;
    projet:uucr_id ?uucr_id;
    projet:uucr_nom ?uucr_nom;
    projet:dep_id ?dep_id;
    projet:dep ?uri_dep_nom;
    projet:aca_id ?aca_id;
    projet:aca ?uri_aca_nom;
    projet:reg_id ?reg_id;
    projet:reg ?uri_reg_nom;
    projet:numero_siren_siret_uai ?numero_siren_siret_uai;
    owl:sameAs ?sameAs;
}

FROM <file:donnees.csv>
WHERE {
	BIND (URI(CONCAT('http://websm.org/institution/', ?libelle_court)) as ?URI)
  BIND (REPLACE(?geolocalisation, '[0-9\\.]*, ', '') as ?longitude)
  BIND (REPLACE(?geolocalisation, ', [0-9\\.]*', '') as ?latitude)
  BIND (URI(?compte_twitter) as ?uri_twitter)
  BIND (URI(?compte_linkedin) as ?uri_linkedin)
  BIND (URI(CONCAT("dbpedia-fr:", REPLACE(?localite, "\\s+", "_"))) as ?uri_localite)
  BIND (URI(CONCAT("dbpedia-fr:", REPLACE(?aca_nom, "\\s+", "_"))) as ?uri_aca_nom)
  BIND (URI(CONCAT("http://localhost:3333/", ?libelle_long)) as ?sameAs)
  BIND (URI(CONCAT("projet:", REPLACE(?reg_nom, "\\s+", "_"))) as ?uri_reg_nom)
  BIND (URI(CONCAT("projet:", REPLACE(?dep_nom, "\\s+", "_"))) as ?uri_dep_nom)
}
