PREFIX projet: <http://websm.org/projet>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ns: <http://www.w3.org/2006/vcard/ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

#Twitter
CONSTRUCT {
  ?URI a foaf:OnlineAccount;
    foaf:accountName ?name;
    foaf:accountServiceHomepage "http://twitter.com/"
}

FROM <file:donnees.csv>
WHERE {
  BIND (REPLACE(?compte_twitter, "https://twitter\\.com/", "") as ?name)
  BIND (URI(?compte_twitter) as ?URI)
}

#LinkedIn
CONSTRUCT {
  ?URI a foaf:OnlineAccount;
    foaf:accountName ?name;
    foaf:accountServiceHomepage "http://www.linkedin.com/"
}

FROM <file:donnees.csv>
WHERE {
  BIND (REPLACE(?compte_linkedin, "(http|https)://[a-z]*\\.linkedin\\.com/", "") as ?name)
  BIND (URI(?compte_linkedin) as ?URI)
}

#Institutions
CONSTRUCT {
	?URI a projet:Institution;
    projet:uai ?uai;
    projet:libelle_court ?libelle_court;
    projet:libelle_long ?libelle_long;
    projet:statut_juridique_court ?statut_juridique_court;
    ns:street-address ?adresse;
    projet:complement_adresse ?complement_adresse;
    ns:postal-code ?code_postal;
    ns:locality ?localite;
    ns:latitude ?latitude;
    ns:longitude ?longitude;
    ns:url ?site_internet;
    foaf:account ?uri_twitter;
    foaf:account ?uri_linkedin;
    projet:identifiant_freebase ?identifiant_freebase;
    projet:identifiant_wikidata ?identifiant_wikidata;
    projet:statut_operateur_lolf ?statut_operateur_lolf;
    projet:libelle_mission_chef_de_file ?libelle_mission_chef_de_file;
    projet:identifiant_programme_lolf_chef_de_file ?identifiant_programme_lolf_chef_de_file;
    projet:libelle_programme_lolf_chef_de_file ?libelle_programme_lolf_chef_de_file;
    projet:identifiants_autres_programmes_lolf ?identifiants_autres_programmes_lolf;
    projet:libelles_autres_programmes_lolf ?libelles_autres_programmes_lolf;
    projet:com_code ?com_code;
    projet:com_nom ?com_nom;
    projet:uucr_id ?uucr_id;
    projet:uucr_nom ?uucr_nom;
    projet:dep_id ?dep_id;
    projet:dep_nom ?dep_nom;
    projet:aca_id ?aca_id;
    projet:aca_nom ?aca_nom;
    projet:reg_id ?reg_id;
    projet:reg_nom ?reg_nom;
    projet:numero_siren_siret_uai ?numero_siren_siret_uai;
}

FROM <file:donnees.csv>
WHERE {
	BIND (URI(CONCAT('http://websm.org/institution/', ?libelle_court)) as ?URI)
  BIND (REPLACE(?geolocalisation, '[0-9\\.]*, ', '') as ?longitude)
  BIND (REPLACE(?geolocalisation, ', [0-9\\.]*', '') as ?latitude)
  BIND (URI(?compte_twitter) as ?uri_twitter)
  BIND (URI(?compte_linkedin) as ?uri_linkedin)
}
