PREFIX projet: <http://websm.org/projet>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ns: <http://www.w3.org/2006/vcard/ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

#Nombre d'institutions de chaque statut juridique (entreprise privée, publique, SARL...)

SELECT ?statut, (COUNT(?statut) as ?nombre)
WHERE {
  ?x rdf:type projet:Institution;
    projet:statut_juridique_court ?statut;
}
GROUP BY ?statut

#Liste de tous les comptes LinkedIn des institutions d'Île-de-France, s'ils existent

SELECT ?uri_linkedin
WHERE
{
  ?x rdf:type projet:Institution;
    ?x foaf:account ?uri_linkedin .
  ?uri_linkedin rdf:type foaf:OnlineAccount;
    foaf:accountServiceHomepage "http://www.linkedin.com/";
}
